In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [42]:
df = pd.read_csv('_data.csv', index_col=0)

In [44]:
df['Метро'] = [row.split(' (')[0] for row in df['Метро'].astype(str)]
df['Метро'] = df['Метро'].str.split('. ')
df

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,...,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,271271157,4,Квартира,"[м, Смоленская]","Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,...,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.00,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,271634126,4,Квартира,"[м, Смоленская]","Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,...,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.50,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,271173086,"4, Оба варианта",Квартира,"[м, Смоленская]","Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384",...,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,272197456,"4, Оба варианта",Квартира,"[м, Смоленская]","Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",...,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,273614615,2,Квартира,"[м, Арбатская]","Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,...,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.90,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,215565511,NaN,Квартира,"[м, Говорово]","Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",35.0/16.4/8.0,10/14,NaN,"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",+79154383401,...,NaN,Совмещенный (1),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",Мещерский лес,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/215565511
23364,274654844,1,Квартира,"[м, Солнцево]","Москва, Производственная улица, 8к1, ш. Боровс...",38.7/16.5/11.0,"5/18, Монолитный",NaN,"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",+79151173402,...,Во двор,Совмещенный (1),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",Лучи,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/274654844
23365,268679909,"2, Оба варианта",Квартира,"[м, Солнцево]","Москва, Боровский проезд, 11",43.1,"5/5, Кирпичный",NaN,"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79653825192,...,На улицу и двор,Совмещенный (1),Можно с детьми,"Мебель на кухне, Душевая кабина, Стиральная ма...",NaN,NaN,NaN,NaN,NaN,https://www.cian.ru/rent/flat/268679909
23366,274807525,2,Квартира,"[м, Солнцево]","Москва, улица Богданова, 6к1, ш. Боровское (3 ...",52.5/10.0,"8/23, Монолитный",наземная,"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79660611965,...,Во двор,"Совмещенный (1), Раздельный (1)",NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",NaN,NaN,2.65,Пасс (3),Да,https://www.cian.ru/rent/flat/274807525
23367,274672243,"2, Оба варианта",Квартира,"[м, Говорово]","Москва, улица Богданова, 2к1, ш. Боровское (3 ...",90.0/48.2/15.5,"6/23, Панельный",NaN,"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",+79623641533,...,Во двор,Раздельный (1),"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Сти...",NaN,NaN,NaN,Пасс (3),Да,https://www.cian.ru/rent/flat/274672243

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23368 entries, 0 to 23367
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID  объявления            23368 non-null  int64
 1   Количество комнат         22327 non-null  object
 2   Тип                       23368 non-null  object
 3   Метро                     22053 non-null  object
 4   Адрес                     23368 non-null  object
 5   Площадь, м2               23368 non-null  object
 6   Дом                       23368 non-null  object
 7   Парковка                  9951 non-null   object
 8   Цена                      23368 non-null  object
 9   Телефоны                  23368 non-null  object
 10  Описание                  23368 non-null  object
 11  Ремонт                    20613 non-null  object
 12  Площадь комнат, м2        14458 non-null  object
 13  Балкон                    15390 non-null  object
 14  Окна                      16755 non-null  object
 15  Санузел                   20696 non-null  object
 16  Можно с детьми/животными  17272 non-null  object
 17  Дополнительно             23011 non-null  object
 18  Название ЖК               5848 non-null   object
 19  Серия дома                2163 non-null   object
 20  Высота потолков, м        11206 non-null  float64
 21  Лифт                      17868 non-null  object
 22  Мусоропровод              12846 non-null  object
 23  Ссылка на объявление      23368 non-null  object
dtypes: float64(1), int64(1), object(22)
memory usage: 4.5+ MB

In [30]:
df.shape

(23368, 24)

In [26]:
df.nunique()

ID  объявления              23368
Количество комнат              24
Тип                             1
Метро                        5866
Адрес                       12850
Площадь, м2                 11255
Дом                          2565
Парковка                        5
Цена                         3922
Телефоны                    13172
Описание                    23078
Ремонт                          4
Площадь комнат, м2           3990
Балкон                         18
Окна                            3
Санузел                        20
Можно с детьми/животными        3
Дополнительно                 528
Название ЖК                  1798
Серия дома                    393
Высота потолков, м             95
Лифт                           34
Мусоропровод                    2
Ссылка на объявление        23368
dtype: int64

In [62]:

df['Square'] = df['Площадь, м2'].str.split('/').str[0]

df['Square'] = pd.to_numeric(df['Square'])

df['Rooms'] = df['Количество комнат'].str.split(',').str[0]

df['Rooms'] = pd.to_numeric(df['Rooms'])

In [63]:
# Избавляемся от выбросов

def remove_outliers(group, column):
    Q1 = group[column].quantile(0.25)
    Q3 = group[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return group[(group[column] >= lower_bound) & (group[column] <= upper_bound)]

df_cleaned = df.groupby('Rooms').apply(remove_outliers, 'Square').reset_index(drop=True)


mean = df_cleaned.groupby('Rooms')['Square'].mean()
mean

/tmp/ipykernel_14229/256090886.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cleaned = df.groupby('Rooms').apply(remove_outliers, 'Square').reset_index(drop=True)

Rooms
1.0     37.002295
2.0     52.892711
3.0     86.202960
4.0    146.487108
5.0    204.533048
6.0    306.899219
Name: Square, dtype: float64

In [79]:
def fill_missing_rooms(row):
    if pd.isna(row['Rooms']):
        
        closest_room_count = mean.sub(row['Square']).abs().idxmin()
        return closest_room_count
    else:
        return row['Rooms']


df['Rooms'] = df.apply(fill_missing_rooms, axis=1)

In [80]:
df['Clear_price'] = df['Цена'].str.split().str[0]
df['Clear_price'] = pd.to_numeric(df['Clear_price'])
df

df_price_clean = df.groupby('Ремонт').apply(remove_outliers, 'Clear_price').reset_index(drop=True)
df_price_clean

price_mean = df_price_clean.groupby('Ремонт')['Clear_price'].mean()
price_mean

def fill_missing_renovation(row):
    if pd.isna(row['Ремонт']):
        
        closest_renov_count = price_mean.sub(row['Clear_price']).abs().idxmin()
        return closest_renov_count
    else:
        return row['Ремонт']


df['Ремонт'] = df.apply(fill_missing_renovation, axis=1)

/tmp/ipykernel_14229/595739740.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_price_clean = df.groupby('Ремонт').apply(remove_outliers, 'Clear_price').reset_index(drop=True)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23368 entries, 0 to 23367
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID  объявления            23368 non-null  int64
 1   Количество комнат         22327 non-null  object
 2   Тип                       23368 non-null  object
 3   Метро                     22053 non-null  object
 4   Адрес                     23368 non-null  object
 5   Площадь, м2               23368 non-null  object
 6   Дом                       23368 non-null  object
 7   Парковка                  9951 non-null   object
 8   Цена                      23368 non-null  object
 9   Телефоны                  23368 non-null  object
 10  Описание                  23368 non-null  object
 11  Ремонт                    23368 non-null  object
 12  Площадь комнат, м2        14458 non-null  object
 13  Балкон                    15390 non-null  object
 14  Окна                      16755 non-null  object
 15  Санузел                   20696 non-null  object
 16  Можно с детьми/животными  17272 non-null  object
 17  Дополнительно             23011 non-null  object
 18  Название ЖК               5848 non-null   object
 19  Серия дома                2163 non-null   object
 20  Высота потолков, м        11206 non-null  float64
 21  Лифт                      17868 non-null  object
 22  Мусоропровод              12846 non-null  object
 23  Ссылка на объявление      23368 non-null  object
 24  Square                    23368 non-null  float64
 25  Rooms                     23368 non-null  float64
 26  Clear_price               23368 non-null  float64
dtypes: float64(4), int64(1), object(22)
memory usage: 5.0+ MB